resources:
- cluster-agent.yaml
patches:
  - patch: |-
      apiVersion: cluster.appdynamics.com/v1alpha1
      kind: Clusteragent
      metadata:
        name: {{ printf "%s-%s" .Release.Name "appdynamics-cluster-agent" | trunc 63 }}   
  - patch: |-
      apiVersion: cluster.appdynamics.com/v1alpha1
      kind: Clusteragent
      metadata:
        name: {{ .Values.clusterAgent.appName | trunc 63 }}