nameOverride: "test"
fullnameOverride: "test"

deploymentMode: PRIMARY

#Cluster Agent image info
imageInfo:
  agentImage: docker.io/appdynamics/cluster-agent
  agentTag: 20.9.0
  operatorImage: docker.io/appdynamics/cluster-agent-operator
  operatorTag: latest
  imagePullPolicy: IfNotPresent
  machineAgentImage: docker.io/appdynamics/machine-agent-analytics
  machineAgentTag: 21.9.0
  machineAgentWinTag: 21.9.0-win-ltsc2019  

# AppDynamics controller info
controllerInfo:
  url: https://apm-foobar.pl.appdynamics.com:443
  account: itau-dev                   
  username: FOO
  password: BAR
  accessKey: FOO123BAR456

# Cluster agent config
clusterAgent:
  appName: "xpto"
  nsToMonitor: [default,kube-node-lease,kube-public,kube-system,appdynamics]
  clusterMetricsSyncInterval: 60
  metadataSyncInterval: 60
  eventUploadInterval: 10
  httpClientTimeout: 30
  podBatchSize: 6
  imagePullSecret: ""
  containerProperties:
    containerBatchSize: 5
    containerParallelRequestLimit: 1
    containerRegistrationInterval: 120
  logProperties:
    logFileSizeMb: 5
    logFileBackups: 3
    logLevel: INFO
  metricProperties:
    metricsSyncInterval: 30
    metricUploadRetryCount: 2
    metricUploadRetryIntervalMilliSeconds: 5

install:
  metrics-server: true    

# instrumentationConfig:
#   enabled: true
#   instrumentationMethod: Env
#   nsToInstrumentRegex: ecom|books|groceries
#   defaultAppName: Ecommerce
#   appNameStrategy: namespace
#   imageInfo:
#     java:
#       image: "docker.io/appdynamics/java-agent:latest"
#       agentMountPath: /opt/appdynamics
#       imagePullPolicy: IfNotPresent
#   instrumentationRules:
#     - namespaceRegex: groceries
#       language: dotnetcore
#       imageInfo:
#         image: "docker.io/appdynamics/dotnet-core-agent:latest"
#         agentMountPath: /opt/appdynamics
#         imagePullPolicy: IfNotPresent
#     - namespaceRegex: books
#       matchString: openmct
#       language: nodejs
#       imageInfo:
#         image: "docker.io/appdynamics/nodejs-agent:20.5.0-alpinev10"
#         agentMountPath: /opt/appdynamics
#         imagePullPolicy: IfNotPresent