apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: opentelemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
    spec:
      containers:
      - name: myapp
        image: quay.io/jpkroehling/generate-span-java:0.1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /opt/observability/otel-javaagent
            name: otel-javaagent        
        command:
          - "-javaagent:/opt/observability/otel-javaagent/opentelemetry-javaagent.jar"
        resources:
          limits:
            cpu: 256m
            memory: 512Mi          
      volumes:
        - name: otel-javaagent
          hostPath: 
            path: /home/otel-javaagent
            type: DirectoryOrCreate        